apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-mongodb
  template:
    metadata:
      labels:
        app: fleetman-mongodb
    spec:
      containers:
      - name: fleetman-mongodb
        image: mongo:3.6.23
        ports:
          - containerPort: 27017
        volumeMounts:
            - mountPath: /data/db
              name: mongo-data
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-pvc