apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  selector:
    app: fleetman-webapp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
    - name: custom-port
      protocol: TCP
      port: 81
      targetPort: 80
      nodePort: 30080
  type: NodePort
