apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
spec:
  selector:
    app: fleetman-api-gateway
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30020
  type: NodePort
