apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  selector:
    app: fleetman-webapp
 ports:
    - name: test1
      protocol: TCP
      port: 80
      targetPort: 80
    - name: test2
      protocol: TCP
      port: 30080
      targetPort: 8080
  type: NodePort
