apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
spec:
  selector:
    app: fleetman-position-tracker
  ports:
    - name: test1
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: test2
      protocol: TCP
      port: 30010
      targetPort: 8080
  type: NodePort