apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  selector:
    app: fleetman-webapp
  ports:
    - name: test1
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
